services:

  sas-api:
    build:
      context: .
      dockerfile: Dockerfile.sas-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3010:3010"
    environment:
      - INTERNAL_API_URL=http://sas-api:8000
    depends_on:
      - sas-api
    restart: unless-stopped
