#!/usr/bin/env python3
"""Simulate the SAS TabBERT embeddings pipeline in Python (generic).

Reads sas_config.json (generated by export_embedding_weights.py) to
determine column roles, encoding maps, and projection matrix — then
builds feature vectors and computes embeddings identically to the SAS
script, but without requiring SAS.

Usage:
    python scripts/simulate_sas_embeddings.py [--csv ...] [--batch-size 5000]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

WEIGHT_DIR = PROJECT_ROOT / "data" / "embeddings" / "tabular"
DEFAULT_INPUT = PROJECT_ROOT / "data" / "samples" / "recuperatory_cycles.csv"
OUTPUT_CSV = WEIGHT_DIR / "sas_embeddings.csv"

CARTOON = r"""
  ╔══════════════════════════════════════════════╗
  ║   SAS TabBERT Simulation (generic)           ║
  ║   [CAT one-hot] → [NUM normalize] → [× W]   ║
  ╚══════════════════════════════════════════════╝
"""


def _load_config(config_path: Path) -> dict:
    with open(config_path) as f:
        return json.load(f)


def _load_data(csv_path: Path) -> list[dict]:
    import csv
    with open(csv_path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _safe_float(v: str, default: float = 0.0) -> float:
    try:
        return float(v.strip()) if v.strip() else default
    except (ValueError, AttributeError):
        return default


def build_features(
    rows: list[dict],
    config: dict,
    batch_size: int = 5000,
) -> tuple[np.ndarray, np.ndarray, list[dict]]:
    cat_cols = config["categorical_cols"]
    num_cols = config["numeric_cols"]
    cat_values = config["cat_values"]
    num_params = config["num_params"]

    n = len(rows)
    n_feat = sum(len(v) for v in cat_values.values()) + len(num_cols)
    X = np.zeros((n, n_feat), dtype=np.float64)
    original_cols = list(rows[0].keys()) if rows else []

    for i, row in enumerate(rows):
        idx = 0
        for col in cat_cols:
            vals = cat_values[col]
            val = row.get(col, "")
            if val in vals:
                X[i, idx + vals.index(val)] = 1.0
            idx += len(vals)

        for col in num_cols:
            v = _safe_float(row.get(col, ""))
            info = num_params[col]
            rng = info["range"]
            X[i, idx] = (v - info["min"]) / rng if rng > 0 else 0.0
            idx += 1

        if (i + 1) % batch_size == 0 or i == 0 or i == n - 1:
            pct = (i + 1) / n * 100
            print(f"  [TabBERT-SAS] Feature row {i + 1:,} / {n:,} ({pct:.0f}%)")

    return X, np.arange(1, n + 1, dtype=np.int64).reshape(-1, 1), rows, original_cols


def _load_projection(proj_path: Path) -> np.ndarray:
    import csv
    with open(proj_path) as f:
        reader = csv.reader(f)
        header = next(reader)
        embed_dim = len(header) - 1
        proj = np.zeros((0, embed_dim))
        for row in reader:
            proj = np.vstack([proj, [float(x) for x in row[1:]]])
    return proj


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Simulate SAS TabBERT embeddings (generic)"
    )
    parser.add_argument("--csv", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--batch-size", type=int, default=5000)
    parser.add_argument("--sample", type=int, default=None,
                        help="Limit rows for testing")
    parser.add_argument("--config-dir", type=Path, default=WEIGHT_DIR)
    args = parser.parse_args()

    print(CARTOON)

    # Load config
    config_path = args.config_dir / "sas_config.json"
    print(f"Reading config from {config_path}...")
    config = _load_config(config_path)
    cat_cols = config["categorical_cols"]
    num_cols = config["numeric_cols"]
    print(f"  {len(cat_cols)} categorical: {cat_cols}")
    print(f"  {len(num_cols)} numeric: {num_cols}")

    # Load data
    print(f"\nReading {args.csv}...")
    rows = _load_data(args.csv)
    if args.sample:
        rows = rows[:args.sample]
    n = len(rows)
    print(f"Loaded {n:,} rows")

    # Load projection matrix
    proj_path = args.config_dir / "sas_projection.csv"
    print(f"\nLoading projection matrix from {proj_path}...")
    proj = _load_projection(proj_path)
    print(f"  Projection: {proj.shape[0]} × {proj.shape[1]}")
    embed_dim = proj.shape[1]
    n_feat = proj.shape[0]

    # Build features
    print(f"\nBuilding feature vectors ({n_feat} dims) in batches...")
    X, row_ids, all_rows, original_cols = build_features(
        rows, config, batch_size=args.batch_size,
    )
    print(f"  Feature matrix: {X.shape}")

    # Compute embeddings in batches
    print(f"\nComputing embeddings ({n_feat}→{embed_dim}) in batches...")
    n_batches = max(1, (n + args.batch_size - 1) // args.batch_size)
    all_embeddings: list[np.ndarray] = []

    for b in range(n_batches):
        s = b * args.batch_size
        e = min((b + 1) * args.batch_size, n)
        X_batch = X[s:e]
        E_batch = X_batch @ proj
        all_embeddings.append(E_batch)
        pct = e / n * 100
        print(f"  Batch {b + 1}/{n_batches}: rows {s + 1:,}–{e:,} ({pct:.0f}%)")

    E = np.vstack(all_embeddings)
    print(f"  Embedding matrix: {E.shape}")

    # Write output (all original columns carried through as metadata)
    print(f"\nWriting {OUTPUT_CSV}...")
    embed_cols = [f"EMB_{j + 1}" for j in range(embed_dim)]
    with open(OUTPUT_CSV, "w", newline="") as f:
        import csv
        w = csv.writer(f)
        w.writerow(["ROW_ID"] + embed_cols + original_cols)
        for i in range(n):
            w.writerow(
                [int(row_ids[i, 0])]
                + [f"{v:.8f}" for v in E[i].tolist()]
                + [all_rows[i].get(c, "") for c in original_cols]
            )

    print(f"  Wrote {n:,} rows × {embed_dim} dims → {OUTPUT_CSV}")
    print("\nDone. Run: python scripts/plot_sas_embeddings.py")


if __name__ == "__main__":
    main()
