/*══════════════════════════════════════════════════════════════════════════
 * TABBERT-STYLE EMBEDDINGS IN SAS  —  Generic Column-Parametrizable
 *══════════════════════════════════════════════════════════════════════════
 *
 *  Approximates TabBERT's [COL]/[VAL] serialization → embedding pipeline
 *  using a linear projection of engineered features (one-hot categories +
 *  normalized numerics).  The projection matrix was pre-trained from
 *  nomic-embed-text representations (see Python export below).
 *
 * ── PREREQUISITES (ONE-TIME) ──────────────────────────────────────────
 *
 *  Step 1 — Export weights & generate table-specific SAS code:
 *
 *      python scripts/export_embedding_weights.py  \
 *          --csv data/samples/recuperatory_cycles.csv
 *
 *    This produces in data/embeddings/tabular/:
 *      sas_weights.xlsx    (49 KB — 4 sheets: Projection, CatMaps,
 *                           NumMaps, Config)
 *      sas_generated.sas   (table-specific DATA step + IML code)
 *      sas_projection.csv  (same projection matrix, CSV format)
 *      sas_cat_maps.csv    (categorical encoding maps)
 *      sas_num_maps.csv    (numeric normalization params)
 *      sas_config.json     (Python simulation config)
 *
 *    ⚠  Only re-run if the input CSV COLUMNS change.  The projection
 *       matrix depends on which columns exist and their categories.
 *
 *  Step 2 — Load the Excel workbook into SAS (manual, one-time):
 *
 *      libname xl excel "data/embeddings/tabular/sas_weights.xlsx";
 *      data proj_raw;  set xl.'Projection'n;  run;
 *      data cat_maps;  set xl.'CatMaps'n;     run;
 *      data num_maps;  set xl.'NumMaps'n;     run;
 *      libname xl clear;
 *
 *    The script below also loads from CSVs automatically, so this step
 *    is optional if you prefer CSV import.
 *
 * ── HOW TO RUN ────────────────────────────────────────────────────────
 *
 *      sas scripts/tabular_embeddings.sas \
 *          -log data/logs/tabular_embeddings.log
 *
 * ── OUTPUT ────────────────────────────────────────────────────────────
 *
 *      data/embeddings/tabular/sas_embeddings.csv
 *      (embeddings + all original columns as metadata)
 *
 *════════════════════════════════════════════════════════════════════════*/

%let ROOT       = ../../data/embeddings/tabular;
%let INPUT_CSV  = ../../data/samples/recuperatory_cycles.csv;
%let OUTPUT_CSV = &ROOT./sas_embeddings.csv;
%let BATCH_SIZE = 5000;

title "TabBERT-style Embeddings in SAS";
footnote "Started: &sysdate &:&systime";

/* ── 1. Load projection matrix (from CSV; or skip if already in WORK) ──── */

%macro ensure_dataset(ds, csv, exists);
  %if %sysfunc(exist(&ds.)) = 0 %then %do;
    %put NOTE: [TabBERT-SAS] &ds. not found — importing from &csv.;
    proc import datafile="&csv." out=&ds. dbms=csv replace;
      getnames=yes;
    run;
  %end;
  %else %do;
    %put NOTE: [TabBERT-SAS] Using pre-loaded dataset &ds.;
  %end;
%mend;

%ensure_dataset(proj_raw, &ROOT./sas_projection.csv);
%ensure_dataset(cat_maps, &ROOT./sas_cat_maps.csv);
%ensure_dataset(num_maps, &ROOT./sas_num_maps.csv);

/* ── 2. Import input data (the cycles / observations to embed) ─────────── */

proc import datafile="&INPUT_CSV."
    out=cycles dbms=csv replace;
    getnames=yes;
    guessingrows=10000;
run;

/* ── 3. Include table-specific feature construction + IML code ───────────
 *  This was generated by export_embedding_weights.py and contains:
 *    a) PROC FORMAT definitions for each categorical column
 *    b) DATA _features step (builds one-hot + normalized features)
 *    c) DATA _meta step (snapshots all original columns)
 *    d) PROC IML (batch-multiply features × projection matrix)
 *─────────────────────────────────────────────────────────────────────────*/

%include "&ROOT./sas_generated.sas";

/* ── 4. Merge metadata + export CSV ────────────────────────────────────── */

proc sql;
    create table sas_embeddings_full as
        select e.*, m.*
        from _embeddings e
        left join _meta m on e.ROW_ID = m._ROWID_
        order by e.ROW_ID;
    drop table _features, _meta, _embeddings;
quit;

proc export data=sas_embeddings_full
    outfile="&OUTPUT_CSV."
    dbms=csv replace;
    putnames=yes;
run;

/* ── 5. Final summary ──────────────────────────────────────────────────── */

proc sql;
    select
        count(*)       as N_CASES,
        "&OUTPUT_CSV." as OUTPUT_FILE
    from sas_embeddings_full;
quit;

title;
footnote;

%put NOTE: ================================================================;
%put NOTE: TabBERT-SAS finished at %sysfunc(datetime(), datetime20.);
%put NOTE: Output: &OUTPUT_CSV.;
%put NOTE: ================================================================;
